[package]
name = "typst-docx"
description = "Typst's DOCX (Microsoft Word) exporter."
version = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
readme = { workspace = true }

[dependencies]
typst-library = { workspace = true }
typst-layout = { workspace = true }
typst-macros = { workspace = true }
typst-ooxml-core = { workspace = true }
typst-syntax = { workspace = true }
typst-timing = { workspace = true }
typst-utils = { workspace = true }
typst-svg = { workspace = true }
comemo = { workspace = true }
ecow = { workspace = true }
hayagriva = { workspace = true }
rustc-hash = { workspace = true }
unicode-math-class = { workspace = true }
zip = { workspace = true }
flate2 = { workspace = true }
time = { workspace = true }

[lints]
workspace = true
