[package]
name = "typst-pptx"
description = "Typst's PPTX (Microsoft PowerPoint) exporter."
version = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
readme = { workspace = true }

[dependencies]
typst-layout = { workspace = true }
typst-library = { workspace = true }
typst-utils = { workspace = true }
ecow = { workspace = true }
rustc-hash = { workspace = true }
time = { workspace = true }
zip = { workspace = true }

[lints]
workspace = true
