[package]
name = "typst-export-common"
description = "Shared infrastructure for Typst exporters."
version = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
readme = "README.md"

[dependencies]
tiny-skia = { workspace = true }
typst-layout = { workspace = true }
typst-library = { workspace = true }
typst-render = { workspace = true }

[lints]
workspace = true
